version: 2
jobs:
  onPullRequest:
    docker:
      - image: heroku/nodejs:latest
    steps:
      - checkout
      - run: ./heartpoints.sh onPullRequest
  onMasterMerge:
    docker:
      - image: heroku/nodejs:latest
    steps:
      - checkout
      - run: ./heartpoints.sh onMasterMerge
workflows:
  version: 2
  pipeline:
    jobs:
      - onPullRequest:
          filters:
            branches:
              ignore: master
      - onMasterMerge:
          filters:
            branches:
              only: master